#!/usr/bin/env bash
set -eu

runtime="${1:?usage: generate-runtime-docs.sh <runtime>}"
versions_file="${VERSIONS_FILE:-generic/${runtime}/versions.yml}"
image_name="${IMAGE_NAME:-ghcr.io/michlip-eu/generic/${runtime}}"
docs_file="${DOCS_FILE:-docs/versions/${runtime}.md}"
docs_dir="$(dirname "$docs_file")"
details_dir="${DETAILS_DIR:-${docs_dir}/${runtime}}"

config() {
  case "$runtime" in
    node)
      display_name="Node.js"
      full_base='node:<version>-bookworm-slim'
      alpine_base='node:<version>-alpine'
      support_note="Node.js odd-numbered lines are short-lived. Prefer active LTS or current even-numbered releases for production."
      ;;
    bun)
      display_name="Bun.js"
      full_base='oven/bun:<version>'
      alpine_base='oven/bun:<version>-alpine'
      support_note="Bun images track pinned upstream releases. Older versions are kept for reproducible rebuilds."
      ;;
    deno)
      display_name="Deno"
      full_base='denoland/deno:debian-<version>'
      alpine_base='denoland/deno:alpine-<version>'
      support_note="Deno images track pinned upstream releases. Older versions are kept for reproducible rebuilds."
      ;;
    python)
      display_name="Python"
      full_base='python:<version>-slim-bookworm'
      alpine_base='python:<version>-alpine'
      support_note="Python images should generally use maintained CPython release lines. Deprecated here means outside the two newest pinned lines in this repository."
      ;;
    java)
      display_name="Java"
      full_base='eclipse-temurin:<version>-jdk-jammy'
      alpine_base='eclipse-temurin:<version>-jdk-alpine'
      support_note="Java images are based on Eclipse Temurin JDK tags. Prefer current or LTS lines such as 21 and 17 when applicable."
      ;;
    rust)
      display_name="Rust"
      full_base='rust:<version>-bookworm'
      alpine_base='rust:<version>-alpine'
      support_note="Rust images track pinned stable Rust releases. Older versions are kept for reproducible rebuilds."
      ;;
    *)
      echo "unknown runtime: $runtime" >&2
      exit 1
      ;;
  esac
}

versions() {
  awk '
    /^[[:space:]]*(older_versions|versions)[[:space:]]*:/ {
      in_versions = 1
      next
    }
    in_versions && /^[^[:space:]-]/ {
      exit
    }
    in_versions && /^[[:space:]]*-/ {
      sub(/^[[:space:]]*-[[:space:]]*/, "")
      sub(/[[:space:]]*#.*/, "")
      gsub(/["'\'']/, "")
      if ($0 != "") {
        print $0
      }
    }
  ' "$versions_file"
}

line_for() {
  local version="$1"
  local major minor

  IFS=. read -r major minor _ <<< "$version"

  case "$runtime" in
    node|java)
      printf '%s\n' "$major"
      ;;
    *)
      printf '%s.%s\n' "$major" "$minor"
      ;;
  esac
}

latest_for_line() {
  local line="$1"
  local version found=""

  while IFS= read -r version; do
    if [[ -z "$found" && "$(line_for "$version")" == "$line" ]]; then
      found="$version"
    fi
  done < <(versions)

  printf '%s\n' "$found"
}

alias_tags() {
  local version="$1"
  local line="$2"
  local latest_version="$3"
  local latest_line_version
  latest_line_version="$(latest_for_line "$line")"

  if [[ "$version" == "$latest_version" ]]; then
    printf '`latest`, `latest-alpine`, `%s`, `%s-alpine`' "$line" "$line"
  elif [[ "$version" == "$latest_line_version" ]]; then
    printf '`%s`, `%s-alpine`' "$line" "$line"
  else
    printf 'None'
  fi
}

status_for() {
  local version="$1"
  local line="$2"
  local current_line="$3"
  local previous_line="$4"
  local latest_line_version
  latest_line_version="$(latest_for_line "$line")"

  if [[ "$line" == "$current_line" && "$version" == "$latest_line_version" ]]; then
    printf 'Current'
  elif [[ "$line" == "$previous_line" && "$version" == "$latest_line_version" ]]; then
    printf 'Supported'
  elif [[ "$line" == "$current_line" || "$line" == "$previous_line" ]]; then
    printf 'Superseded'
  else
    printf 'Deprecated'
  fi
}

write_version_doc() {
  local version="$1"
  local line="$2"
  local latest_version="$3"
  local current_line="$4"
  local previous_line="$5"
  local generated_date="$6"
  local aliases status details_file

  aliases="$(alias_tags "$version" "$line" "$latest_version")"
  status="$(status_for "$version" "$line" "$current_line" "$previous_line")"
  details_file="${details_dir}/${version}.md"

  {
    cat <<EOF
<!-- generated by .github/scripts/generate-runtime-docs.sh; do not edit by hand -->

# ${display_name} ${version}

[Back to ${display_name} versions](../${runtime}.md)

Last generated: ${generated_date}

## Status

| Field | Value |
| --- | --- |
| Runtime | ${display_name} |
| Version | \`${version}\` |
| Release line | \`${line}\` |
| Status | ${status} |
| Architectures | \`linux/amd64\`, \`linux/arm64\` |
| Variants | \`full\`, \`alpine\` |

## Tags

| Variant | Base image | Published tag | Pull command |
| --- | --- | --- | --- |
| \`full\` | \`${full_base//<version>/$version}\` | \`${image_name}:${version}\` | \`docker pull ${image_name}:${version}\` |
| \`alpine\` | \`${alpine_base//<version>/$version}\` | \`${image_name}:${version}-alpine\` | \`docker pull ${image_name}:${version}-alpine\` |

## Alias Tags

EOF

    if [[ "$aliases" == "None" ]]; then
      cat <<EOF
This version does not publish any alias tags. Use the exact version tags above.

EOF
    else
      cat <<EOF
This version also publishes:

${aliases}

EOF
    fi

    cat <<EOF
## Notes

${support_note}
EOF
  } > "$details_file"
}

config

if [[ ! -f "$versions_file" ]]; then
  echo "missing versions file: $versions_file" >&2
  exit 1
fi

resolved_versions=()
while IFS= read -r version; do
  resolved_versions+=("$version")
done < <(versions)
latest_version="${resolved_versions[0]:-}"
current_line=""
previous_line=""
seen_lines="|"

for version in "${resolved_versions[@]}"; do
  line="$(line_for "$version")"
  if [[ "$seen_lines" != *"|$line|"* ]]; then
    seen_lines="${seen_lines}${line}|"
    if [[ -z "$current_line" ]]; then
      current_line="$line"
    elif [[ -z "$previous_line" ]]; then
      previous_line="$line"
      break
    fi
  fi
done
generated_date="$(date -u +%F)"

if [[ -z "$latest_version" || -z "$current_line" ]]; then
  echo "not enough versions to generate docs for $runtime" >&2
  exit 1
fi

mkdir -p "$docs_dir" "$details_dir"
find "$details_dir" -maxdepth 1 -type f -name '*.md' -delete

{
  cat <<EOF
<!-- generated by .github/scripts/generate-runtime-docs.sh; do not edit by hand -->

# ${display_name} Docker Images

Last generated: ${generated_date}

Images are published to:

\`\`\`text
${image_name}
\`\`\`

The workflow builds every pinned ${display_name} version for both \`linux/amd64\`
and \`linux/arm64\`.

## Variants

| Variant | Base image pattern | Tags | Contents |
| --- | --- | --- | --- |
| \`full\` | \`${full_base}\` | \`latest\`, \`${current_line}\`, \`${latest_version}\` | Official runtime image with Debian or default upstream tooling. |
| \`alpine\` | \`${alpine_base}\` | \`latest-alpine\`, \`${current_line}-alpine\`, \`${latest_version}-alpine\` | Official Alpine runtime image where upstream publishes one. |

## Tag Rules

For each exact version, CI publishes both variants:

\`\`\`text
${image_name}:<version>
${image_name}:<version>-alpine
\`\`\`

The newest patch in each release line also gets line aliases:

\`\`\`text
${image_name}:<line>
${image_name}:<line>-alpine
\`\`\`

The newest resolved version also gets latest aliases:

\`\`\`text
${image_name}:latest
${image_name}:latest-alpine
\`\`\`

## Status Meanings

| Status | Meaning |
| --- | --- |
| Current | Newest pinned version on the newest pinned release line. Prefer this for new work. |
| Supported | Newest pinned version on another current pinned line. |
| Superseded | Older patch in a current pinned release line. Kept for reproducibility. |
| Deprecated | Older release line. Kept only for legacy rebuilds. |

${support_note}

## Published Versions

| Version | Full image tag | Alpine image tag | Alias tags | Status |
| --- | --- | --- | --- | --- |
EOF

  while IFS= read -r version; do
    line="$(line_for "$version")"
    aliases="$(alias_tags "$version" "$line" "$latest_version")"
    status="$(status_for "$version" "$line" "$current_line" "${previous_line:-}")"
    write_version_doc "$version" "$line" "$latest_version" "$current_line" "${previous_line:-}" "$generated_date"
    printf '| [`%s`](%s/%s.md) | `%s` | `%s-alpine` | %s | %s |\n' \
      "$version" "$runtime" "$version" "$version" "$version" "$aliases" "$status"
  done < <(versions)

  cat <<EOF

## Version Sources

CI refreshes this runtime from every matching upstream release git tag, then
merges those discovered versions with pinned versions in
\`generic/${runtime}/versions.yml\`.
EOF
} > "$docs_file"
