#!/usr/bin/env bash
set -euo pipefail

versions_file="${VERSIONS_FILE:-generic/golang/versions.yml}"
docs_file="${DOCS_FILE:-docs/versions/golang.md}"
image_name="${IMAGE_NAME:-ghcr.io/michlip-eu/generic/golang}"

versions() {
  awk '
    /^[[:space:]]*older_versions[[:space:]]*:/ {
      in_versions = 1
      next
    }
    in_versions && /^[^[:space:]-]/ {
      exit
    }
    in_versions && /^[[:space:]]*-/ {
      sub(/^[[:space:]]*-[[:space:]]*/, "")
      sub(/[[:space:]]*#.*/, "")
      gsub(/["'\'']/, "")
      if ($0 != "") {
        print $0
      }
    }
  ' "$versions_file"
}

minor_for() {
  printf '%s\n' "$1" | cut -d. -f1,2
}

latest_for_minor() {
  local minor="$1"
  versions | awk -v minor="$minor" 'index($0, minor ".") == 1 { print; exit }'
}

alias_tags() {
  local version="$1"
  local minor="$2"
  local latest_version="$3"
  local latest_minor_version
  latest_minor_version="$(latest_for_minor "$minor")"

  if [[ "$version" == "$latest_version" ]]; then
    printf '`latest`, `latest-alpine`, `%s`, `%s-alpine`' "$minor" "$minor"
  elif [[ "$version" == "$latest_minor_version" ]]; then
    printf '`%s`, `%s-alpine`' "$minor" "$minor"
  else
    printf 'None'
  fi
}

status_for() {
  local version="$1"
  local minor="$2"
  local supported_current="$3"
  local supported_previous="$4"
  local latest_minor_version
  latest_minor_version="$(latest_for_minor "$minor")"

  if [[ "$minor" == "$supported_current" && "$version" == "$latest_minor_version" ]]; then
    printf 'Current'
  elif [[ "$minor" == "$supported_previous" && "$version" == "$latest_minor_version" ]]; then
    printf 'Supported'
  elif [[ "$minor" == "$supported_current" || "$minor" == "$supported_previous" ]]; then
    printf 'Superseded'
  else
    printf 'Deprecated'
  fi
}

if [[ ! -f "$versions_file" ]]; then
  echo "missing versions file: $versions_file" >&2
  exit 1
fi

latest_version="$(versions | head -n 1)"
supported_current="$(versions | cut -d. -f1,2 | awk '!seen[$0]++' | head -n 1)"
supported_previous="$(versions | cut -d. -f1,2 | awk '!seen[$0]++' | sed -n '2p')"
reviewed_date="$(date -u +%F)"

if [[ -z "$latest_version" || -z "$supported_current" || -z "$supported_previous" ]]; then
  echo "not enough versions to generate docs" >&2
  exit 1
fi

mkdir -p "$(dirname "$docs_file")"

{
  cat <<EOF
<!-- generated by .github/scripts/generate-golang-docs.sh; do not edit by hand -->

# Golang Docker Images

Last generated: ${reviewed_date}

Images are published to:

\`\`\`text
${image_name}
\`\`\`

For this repository, \`ghcr.io/<owner>/<repo>/golang\` resolves to
\`${image_name}\`.

The workflow builds every pinned Go version for both \`linux/amd64\` and
\`linux/arm64\`.

## Variants

| Variant | Base image | Tags | Contents |
| --- | --- | --- | --- |
| \`full\` | \`debian:bookworm-slim\` | \`latest\`, \`${supported_current}\`, \`${latest_version}\` | Go plus common build tools: Git, SSH client, C/C++ compilers, Make, curl, and pkg-config. |
| \`alpine\` | \`alpine:latest\` | \`latest-alpine\`, \`${supported_current}-alpine\`, \`${latest_version}-alpine\` | Smaller Alpine image with Go and the minimum install/download tooling. |

## Tag Rules

For each exact version, CI publishes both variants:

\`\`\`text
${image_name}:<version>
${image_name}:<version>-alpine
\`\`\`

The newest patch in each Go line also gets minor aliases:

\`\`\`text
${image_name}:<major>.<minor>
${image_name}:<major>.<minor>-alpine
\`\`\`

The newest resolved stable Go version also gets latest aliases:

\`\`\`text
${image_name}:latest
${image_name}:latest-alpine
\`\`\`

Commit-specific tags are published as:

\`\`\`text
${image_name}:<version>-<sha>
${image_name}:<version>-alpine-<sha>
\`\`\`

## Status Meanings

Go's release policy supports a release line until there are two newer release
lines. See the official policy at <https://go.dev/doc/devel/release#policy>.

| Status | Meaning |
| --- | --- |
| Current | Newest pinned Go patch on the newest supported release line. Prefer this for new work. |
| Supported | Newest pinned Go patch on another currently supported release line. Acceptable when you cannot move to current yet. |
| Superseded | Older patch in a supported release line. The image exists for reproducibility, but new builds should move to that line's newest patch. |
| Deprecated | Release line is no longer supported by the Go project. Keep only for legacy rebuilds. |

As of ${reviewed_date}, the supported Go lines in this repository are
\`${supported_current}\` and \`${supported_previous}\`. Older lines are deprecated.

## Published Versions

| Go version | Full image tag | Alpine image tag | Alias tags | Status |
| --- | --- | --- | --- | --- |
EOF

  while IFS= read -r version; do
    minor="$(minor_for "$version")"
    aliases="$(alias_tags "$version" "$minor" "$latest_version")"
    status="$(status_for "$version" "$minor" "$supported_current" "$supported_previous")"
    printf '| `%s` | `%s` | `%s-alpine` | %s | %s |\n' \
      "$version" "$version" "$version" "$aliases" "$status"
  done < <(versions)

  cat <<EOF

## Build Schedule

CI/CD runs on pushes, pull requests, manual dispatch, and every Monday at
00:00 UTC. The scheduled run refreshes \`generic/golang/versions.yml\`, commits
newly discovered Go versions, regenerates this page, and builds every pinned
version and variant.
EOF
} > "$docs_file"
